
name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: |
         touch .env
         echo "${{ secrets.PROD_ENV_FILE }}" > .env
    # CD when there is change in the github then it will restart the EC2 server 
    #(reinstall the node module, recreate env file and the secrets in the .envfile)     
    - run: pm2 restart BackendAPI;
